apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  sources:
  
    - repoURL: https://charts.bitnami.com/bitnami
      chart: kafka
      targetRevision: 17.2.3
      helm:
        valueFiles:
          - $values/Common/kafka-values.yaml


    - repoURL: 'https://github.com/maheshgowdamg/Argocd-deploy.git'
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

