apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:

    # Helm chart source
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 18.3.1
      helm:
        valueFiles:
          - $values/Common/redis-values.yaml

    #  Values repo source
    - repoURL: 'https://github.com/maheshgowdamg/Argocd-deploy.git'
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

