loki:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 1000Mi
    limits:
      cpu: 800m
      memory: 3000Mi
  config:
    limits_config:
      retention_period: 120h
    compactor:
      compaction_interval: 5m
      shared_store: filesystem
      retention_enabled: true
      retention_delete_delay: 5m
      retention_delete_worker_count: 15

promtail:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  extraScrapeConfigs: |
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        # Scrape all namespaces
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: .*
        # Label the pod name
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        # Label the container name
        - source_labels: [__meta_kubernetes_container_name]
          target_label: container
