grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    size: 5Gi

  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-grafana-kube-pr-prometheus:9090
      isDefault: true

prometheus:
  prometheusSpec:
    logFormat: json
    logLevel: warn
    retention: 7d
    retentionSize: 7GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi

    # ✅ PostgreSQL scrape job with full features
    additionalScrapeConfigs:
      - job_name: "postgresql-monitoring"
        metrics_path: /metrics         # Explicit (default is /metrics, but clearer to keep)
        scrape_interval: 30s           # Frequency of scraping
        scrape_timeout: 30s            # Timeout (≤ scrape_interval)

        static_configs:
          - targets:
              - postgresql-primary-metrics.dev.svc.cluster.local:9187
              - postgresql-read-metrics.dev.svc.cluster.local:9187

        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: postgresql-primary-metrics.dev.svc.cluster.local:9187


        - job_name: "mongodb-monitoring"
        metrics_path: /metrics
        scrape_interval: 30s
        scrape_timeout: 30s
        static_configs:
          - targets:
              - mongodb-metrics.dev.svc.cluster.local:9216
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
          - target_label: __address__
            replacement: mongodb-metrics.dev.svc.cluster.local:9216
