grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    size: 5Gi

  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-grafana-kube-pr-prometheus:9090
      isDefault: true

prometheus:
  prometheusSpec:
    logFormat: json
    logLevel: warn
    retention: 7d
    retentionSize: 7GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi

    # ✅ Add PostgreSQL scrape job
    additionalScrapeConfigs:
      - job_name: "postgresql"
        scrape_interval: 30s
        static_configs:
          - targets:
              - "postgresql-primary-metrics.dev.svc.cluster.local:9187"
              - "postgresql-read-metrics.dev.svc.cluster.local:9187"

